window-length: 30
data-set: './src/data/hh103-two-days.txt'
N: 2
threshold: 0.3
kernel-param: 15
regularization-param: 0.5
exclude-other: true
max-cp-match-interval: 2
kn-results-location: './src/data/knowledge-driven/hh103-two-days.json'
only-DD: true
only-KD: false
DD-and-KD: false
features: [WindowDurationFeature, MostFrequentSensorFeature,
          DominantLocationFeature, NumberOfTransitionsFeature, CountOfEventsFeature, NumberSensorChangesFeature,
          TimeBetweenEventsFeature('proportional')]
