source-file: ./src/data/hh103-with-locations-only-activations_slice.txt
window-length: 30
N: 3
changepoint-window-step: 0
exclude-other: true
threshold:
    max: 0.35
    min: 0.10
    step: 0.02
max-cp-match-interval: 3
kernel-param-grid: [5, 7.5]
regularization-param-grid: [2, 5]
features: [WindowDurationFeature,
           MostRecentSensorFeature, MostFrequentSensorFeature, LastSensorLocationFeature,
           DominantLocationFeature, NumberOfTransitionsFeature,
           EntropyFeature, TemporalEntropyFeature,
           CountOfEventsFeature('absolute'), NumberSensorChangesFeature('absolute'),
           EachSensorLastActivationFeature,
           StatsTimeBetweenActivations('absolute')]

