source-file: ./src/data/hh103-two-days.txt
window-length: 30
N: 3
exclude-other: true
threshold:
    max: 0.5
    step: 0.02
max-cp-match-interval: 8
kernel-param-grid: [10, 15]
regularization-param-grid: [0.1, 0.2]
features: [WindowDurationFeature, MostRecentSensorFeature, MostFrequentSensorFeature, LastSensorLocationFeature,
           DominantLocationFeature, NumberOfTransitionsFeature, EntropyFeature, CountOfEventsFeature, EachSensorLastActivationFeature,
           TimeBetweenEventsFeature('absolute'), TimeBetweenEventsFeature('proportional')]

