source-file: ./src/data/hh103-two-days.txt
window-length: 30
N: 3
changepoint-window-step: 0
exclude-other: true
threshold:
    max: 0.35
    min: 0.05
    step: 0.05
max-cp-match-interval: 9
kernel-param-grid: [5, 7.5, 10, 15]
regularization-param-grid: [0.8, 0.9, 1, 2, 5]
features: [MostFrequentSensorFeature, DominantLocationFeature,
           NumberOfTransitionsFeature, CountOfEventsFeature, ProportionSensorChangesFeature,
           EachSensorLastActivationFeature, TimeBetweenEventsFeature('proportional')]

